---
- block:
  - name: "node: install node and npm"
    apt: pkg='{{ item }}' state=present
    with_items:
      - nodejs
      - npm
      - build-essential

  - name: "node: upgrade node and npm to latest stable versions"
    shell: npm cache clean -f && npm install -g n && n 8.12.0 && npm i -g npm@latest

  - name: "node: install global laravel-echo-server"
    shell: npm install -g laravel-echo-server

  when: services.websockets == true
